### ISSUE TITLE
Tick at the close of text string causes error after editing - Encoding consideration

### ISSUE THREAD

**Issue by rricetester** [icemicro/icecube#34]
I don't think this is a bug, but should be documented as a consideration when supplying input to the client endpoint.sh.

When I run the mqtt example with the client file endpoint.sh unmodified after downloading from the repository ('hello world' string text), the string is displayed in iTerm (using fernet) with no problems. 

Then, when I modified the text string in the Mac TextEdit application to 'testing 123', ticks were encoded differently from the original (even if not modified), which caused an error. I confirmed this by viewing the text string in TextMate and the ticks were encoded differently after editing in TextEdit. 

It may not be a bug, but may be a usability issue or compatibility issue with users that needs to be documented. It's a subtle difference that may not be noticed immediately. I'm thinking of the use case where a Java client might send a text string using encoding that is not recognized. Although, in the case mentioned above, I saw this just using a text editor. 

I do plan to test with a different form of input in the near future. 
Before, with no editing of text in TextEdit:
![screen shot 2017-11-13 at 11 38 22 am](https://user-images.githubusercontent.com/31495226/32740099-72aade0e-c867-11e7-8849-a4cbebabe0c3.png)

After, with just adding the character "2" to the end of the string in TestEdit:
![screen shot 2017-11-13 at 11 39 35 am](https://user-images.githubusercontent.com/31495226/32740147-9cf0c76e-c867-11e7-9231-96fa6c42883a.png)

Thanks!

**Comment by emadrid** [comment]
closing due to this not being related to icecore functionality.
