### ISSUE TITLE
ICE Cube Service Errors

### ISSUE THREAD

**Issue by rricetester** [icemicro/icecube#35]
I am trying to run the docker example shown below:
![screen shot 2017-11-14 at 10 51 39 am](https://user-images.githubusercontent.com/31495226/32792878-1d027584-c92a-11e7-8c64-2fba55d1b8d8.png)
but get this result instead of what is indicated as the expected result:
![screen shot 2017-11-14 at 10 51 51 am](https://user-images.githubusercontent.com/31495226/32792933-386a1908-c92a-11e7-847e-6f65ac03301e.png)
I have downloaded the most current image from the repository. Any ideas? Thanks!

**Comment by emadrid** [comment]
It doesn't seem you have the latest image.  run `$ docker pull icemicro/icecube` please.

**Comment by rricetester** [comment]
Thanks, Erik.  Will do.

Randy
