### ISSUE TITLE
Discrepancy between Docker code at top (Getting Started) vs Installation

### ISSUE THREAD

**Issue by rricetester** [icemicro/icecube#36]
It seems that the port numbers are different.
Getting Started:
![screen shot 2017-11-14 at 10 51 39 am](https://user-images.githubusercontent.com/31495226/32793222-ec4b0680-c92a-11e7-9f8f-e3ed2bc3b9d9.png)
Installation:
![screen shot 2017-11-14 at 10 57 47 am](https://user-images.githubusercontent.com/31495226/32793241-f578b888-c92a-11e7-9506-d152c401cd81.png)

**Comment by emadrid** [comment]
They are different.  The getting started snippets are meant to demonstrate the Icecube instantiation with variable ports.  See https://github.com/icemicro/icecube#examples to encrypt traffic between containers.  Thanks for the feedback!

**Comment by emadrid** [comment]
#37
